// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type KvmEventsVcpuMetrics struct {
	_           structs.HostLayout
	ExitCount   uint64
	LastExitTs  uint64
	TotalWaitNs uint64
}

// LoadKvmEvents returns the embedded CollectionSpec for KvmEvents.
func LoadKvmEvents() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KvmEventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load KvmEvents: %w", err)
	}

	return spec, err
}

// LoadKvmEventsObjects loads KvmEvents and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*KvmEventsObjects
//	*KvmEventsPrograms
//	*KvmEventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadKvmEventsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadKvmEvents()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// KvmEventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KvmEventsSpecs struct {
	KvmEventsProgramSpecs
	KvmEventsMapSpecs
	KvmEventsVariableSpecs
}

// KvmEventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KvmEventsProgramSpecs struct {
	HandleKvmDirtyRingPush *ebpf.ProgramSpec `ebpf:"handle_kvm_dirty_ring_push"`
	HandleKvmEntry         *ebpf.ProgramSpec `ebpf:"handle_kvm_entry"`
	HandleKvmExit          *ebpf.ProgramSpec `ebpf:"handle_kvm_exit"`
	HandleKvmInjVirq       *ebpf.ProgramSpec `ebpf:"handle_kvm_inj_virq"`
	HandleKvmMmuPageFault  *ebpf.ProgramSpec `ebpf:"handle_kvm_mmu_page_fault"`
	HandleMmFaultKprobe    *ebpf.ProgramSpec `ebpf:"handle_mm_fault_kprobe"`
}

// KvmEventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KvmEventsMapSpecs struct {
	ExitCounts *ebpf.MapSpec `ebpf:"exit_counts"`
	TargetPids *ebpf.MapSpec `ebpf:"target_pids"`
	VcpuStats  *ebpf.MapSpec `ebpf:"vcpu_stats"`
}

// KvmEventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type KvmEventsVariableSpecs struct {
}

// KvmEventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadKvmEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type KvmEventsObjects struct {
	KvmEventsPrograms
	KvmEventsMaps
	KvmEventsVariables
}

func (o *KvmEventsObjects) Close() error {
	return _KvmEventsClose(
		&o.KvmEventsPrograms,
		&o.KvmEventsMaps,
	)
}

// KvmEventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadKvmEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type KvmEventsMaps struct {
	ExitCounts *ebpf.Map `ebpf:"exit_counts"`
	TargetPids *ebpf.Map `ebpf:"target_pids"`
	VcpuStats  *ebpf.Map `ebpf:"vcpu_stats"`
}

func (m *KvmEventsMaps) Close() error {
	return _KvmEventsClose(
		m.ExitCounts,
		m.TargetPids,
		m.VcpuStats,
	)
}

// KvmEventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadKvmEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type KvmEventsVariables struct {
}

// KvmEventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadKvmEventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type KvmEventsPrograms struct {
	HandleKvmDirtyRingPush *ebpf.Program `ebpf:"handle_kvm_dirty_ring_push"`
	HandleKvmEntry         *ebpf.Program `ebpf:"handle_kvm_entry"`
	HandleKvmExit          *ebpf.Program `ebpf:"handle_kvm_exit"`
	HandleKvmInjVirq       *ebpf.Program `ebpf:"handle_kvm_inj_virq"`
	HandleKvmMmuPageFault  *ebpf.Program `ebpf:"handle_kvm_mmu_page_fault"`
	HandleMmFaultKprobe    *ebpf.Program `ebpf:"handle_mm_fault_kprobe"`
}

func (p *KvmEventsPrograms) Close() error {
	return _KvmEventsClose(
		p.HandleKvmDirtyRingPush,
		p.HandleKvmEntry,
		p.HandleKvmExit,
		p.HandleKvmInjVirq,
		p.HandleKvmMmuPageFault,
		p.HandleMmFaultKprobe,
	)
}

func _KvmEventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kvmevents_bpfel.o
var _KvmEventsBytes []byte
